import { Category, Product, BlogPost } from "./types";

// NOTE: This file stands in for Prisma queries so the storefront is fully
// browsable with zero DB setup. Once Postgres is connected, replace each
// export with a `prisma.product.findMany(...)` call — the shapes match
// prisma/schema.prisma 1:1. See prisma/seed.ts for the loader that turns
// this same data into real rows.

const img = (seed: string) => `https://picsum.photos/seed/${seed}/900/1100`;

export const categories: Category[] = [
  { id: "c1", name: "Women's Fashion", slug: "womens-fashion", description: "Curated dresses, tops and everyday wear picked for how they photograph and how they wear.", bannerImage: img("womens-fashion") },
  { id: "c2", name: "Men's Fashion", slug: "mens-fashion", description: "Wardrobe staples and statement pieces for a clean, modern look.", bannerImage: img("mens-fashion") },
  { id: "c3", name: "Shoes", slug: "shoes", description: "Sneakers, heels and everyday shoes across every budget.", bannerImage: img("shoes") },
  { id: "c4", name: "Jewelry", slug: "jewelry", description: "Fine and fashion jewelry for gifting and everyday wear.", bannerImage: img("jewelry") },
  { id: "c5", name: "Watches", slug: "watches", description: "Analog, smart and statement watches.", bannerImage: img("watches") },
  { id: "c6", name: "Bags", slug: "bags", description: "Totes, crossbody and work bags.", bannerImage: img("bags") },
  { id: "c7", name: "Beauty", slug: "beauty", description: "Makeup and beauty tools worth the hype.", bannerImage: img("beauty") },
  { id: "c8", name: "Skincare", slug: "skincare", description: "Routines and actives that actually work.", bannerImage: img("skincare") },
  { id: "c9", name: "Home Decor", slug: "home-decor", description: "Small pieces that change a room.", bannerImage: img("home-decor") },
  { id: "c10", name: "Kitchen", slug: "kitchen", description: "Tools that make cooking faster and better.", bannerImage: img("kitchen") },
  { id: "c11", name: "Technology", slug: "technology", description: "Gadgets and accessories worth buying.", bannerImage: img("technology") },
  { id: "c12", name: "Fitness", slug: "fitness", description: "Gear for home and gym workouts.", bannerImage: img("fitness") },
];

export const products: Product[] = [
  {
    id: "p1",
    name: "Everyday Linen Wrap Dress",
    slug: "everyday-linen-wrap-dress",
    brand: "Nova & Co.",
    categorySlug: "womens-fashion",
    price: 1499,
    oldPrice: 2199,
    discountPct: 32,
    description:
      "A breathable linen-blend wrap dress designed for warm-weather days and easy layering. Cut for movement, with a flattering tie waist and a hem that photographs well from every angle.",
    features: ["Linen-cotton blend", "Adjustable wrap tie", "Machine washable", "True to size"],
    specs: { Material: "55% Linen, 45% Cotton", Fit: "Regular", Care: "Machine wash cold", Length: "Midi" },
    pros: ["Breathable in heat", "Flattering silhouette", "Easy to dress up or down"],
    cons: ["Wrinkles easily", "Runs slightly long for petite frames"],
    faqs: [
      { question: "Does it run true to size?", answer: "Yes, most reviewers order their usual size." },
      { question: "Is it see-through?", answer: "No, the linen blend has a full lining." },
    ],
    rating: 4.6,
    reviewCount: 812,
    images: [img("linen-dress-1"), img("linen-dress-2"), img("linen-dress-3")],
    pinterestImage: img("linen-dress-pin"),
    pinterestTitle: "Effortless Linen Wrap Dress for Summer",
    pinterestDesc: "The wrap dress everyone's saving this season — breathable, flattering, under ₹1500.",
    tags: ["dresses", "summer", "linen", "wrap-dress"],
    affiliateNetwork: "AMAZON",
    affiliateUrl: "https://www.amazon.in/dp/EXAMPLE1?tag=trendnest-21",
    isFeatured: true,
    isTrending: true,
  },
  {
    id: "p2",
    name: "Classic Oxford Cotton Shirt",
    slug: "classic-oxford-cotton-shirt",
    brand: "Harrow",
    categorySlug: "mens-fashion",
    price: 1299,
    oldPrice: 1799,
    discountPct: 28,
    description:
      "A tailored-fit oxford shirt that works for the office and the weekend. Structured collar, mother-of-pearl buttons, and a weave that holds its shape wash after wash.",
    features: ["100% cotton oxford weave", "Tailored fit", "Button-down collar", "Pre-shrunk"],
    specs: { Material: "100% Cotton", Fit: "Tailored", Care: "Machine wash cold", Collar: "Button-down" },
    pros: ["Doesn't wrinkle easily", "Good weight for AC offices"],
    cons: ["Tailored fit runs slim — size up if in doubt"],
    faqs: [{ question: "Is this shirt see-through?", answer: "No, the oxford weave is opaque." }],
    rating: 4.5,
    reviewCount: 634,
    images: [img("oxford-shirt-1"), img("oxford-shirt-2")],
    pinterestImage: img("oxford-shirt-pin"),
    pinterestTitle: "The Only Oxford Shirt You Need This Year",
    pinterestDesc: "Tailored fit, all-day comfort, works with everything in your closet.",
    tags: ["shirts", "formal", "office-wear"],
    affiliateNetwork: "FLIPKART",
    affiliateUrl: "https://www.flipkart.com/example2",
    isBestSeller: true,
  },
  {
    id: "p3",
    name: "Cloudstep Running Sneakers",
    slug: "cloudstep-running-sneakers",
    brand: "Aeroform",
    categorySlug: "shoes",
    price: 2799,
    oldPrice: 3999,
    discountPct: 30,
    description:
      "Lightweight running sneakers with a responsive foam midsole and breathable knit upper — built for daily miles or all-day wear.",
    features: ["Breathable knit upper", "Responsive foam midsole", "Rubber outsole", "Reflective trims"],
    specs: { Weight: "220g (UK 8)", "Sole": "Rubber", Closure: "Lace-up" },
    pros: ["Great cushioning for the price", "True to size"],
    cons: ["Limited color options", "Not fully waterproof"],
    faqs: [{ question: "Good for running or just casual wear?", answer: "Both — it's a versatile daily trainer." }],
    rating: 4.7,
    reviewCount: 1204,
    images: [img("sneakers-1"), img("sneakers-2"), img("sneakers-3")],
    pinterestImage: img("sneakers-pin"),
    pinterestTitle: "These ₹2799 Sneakers Feel Like Clouds",
    pinterestDesc: "The most-saved running shoe on Pinterest right now — here's why.",
    tags: ["sneakers", "running", "shoes-under-3000"],
    affiliateNetwork: "AMAZON",
    affiliateUrl: "https://www.amazon.in/dp/EXAMPLE3?tag=trendnest-21",
    isTrending: true,
    isBestSeller: true,
  },
  {
    id: "p4",
    name: "Layered Gold-Plated Necklace Set",
    slug: "layered-gold-plated-necklace-set",
    brand: "Lumière",
    categorySlug: "jewelry",
    price: 899,
    oldPrice: 1499,
    discountPct: 40,
    description:
      "A three-layer gold-plated necklace set that adds instant polish to any outfit — tarnish-resistant coating for everyday wear.",
    features: ["18k gold plated", "Tarnish resistant", "Adjustable chain length", "Hypoallergenic"],
    specs: { Plating: "18k Gold", Length: "14-18 inch adjustable" },
    pros: ["Doesn't turn skin green", "Great gifting option"],
    cons: ["Delicate clasp — handle gently"],
    faqs: [{ question: "Will it tarnish?", answer: "The coating is tarnish-resistant with proper care." }],
    rating: 4.4,
    reviewCount: 356,
    images: [img("necklace-1"), img("necklace-2")],
    pinterestImage: img("necklace-pin"),
    pinterestTitle: "Layered Necklace Set Under ₹900",
    pinterestDesc: "The dupe for a $200 layered necklace — tarnish resistant and hypoallergenic.",
    tags: ["jewelry", "necklace", "gifts"],
    affiliateNetwork: "MEESHO",
    affiliateUrl: "https://www.meesho.com/example4",
    isNewArrival: true,
  },
  {
    id: "p5",
    name: "Matte Ceramic Watch — Minimal Dial",
    slug: "matte-ceramic-watch-minimal-dial",
    brand: "Ferro",
    categorySlug: "watches",
    price: 3499,
    oldPrice: 4999,
    discountPct: 30,
    description:
      "A minimal-dial watch with a scratch-resistant ceramic bezel and Japanese quartz movement — the kind that goes with everything.",
    features: ["Japanese quartz movement", "Ceramic bezel", "Sapphire-coated glass", "5ATM water resistant"],
    specs: { Movement: "Quartz", "Water Resistance": "5ATM", "Case Diameter": "40mm" },
    pros: ["Scratch resistant", "Understated design"],
    cons: ["Metal band runs slightly loose — links can be removed"],
    faqs: [{ question: "Can I swim with it?", answer: "5ATM handles splashes and swimming, not diving." }],
    rating: 4.8,
    reviewCount: 289,
    images: [img("watch-1"), img("watch-2")],
    pinterestImage: img("watch-pin"),
    pinterestTitle: "Minimal Ceramic Watch Everyone's Saving",
    pinterestDesc: "Scratch-resistant, understated, and under ₹3500.",
    tags: ["watches", "minimal", "unisex"],
    affiliateNetwork: "AJIO",
    affiliateUrl: "https://www.ajio.com/example5",
    isFeatured: true,
  },
  {
    id: "p6",
    name: "Structured Canvas Tote",
    slug: "structured-canvas-tote",
    brand: "Fielder",
    categorySlug: "bags",
    price: 1199,
    oldPrice: 1699,
    discountPct: 29,
    description:
      "A structured canvas tote with a leather-trimmed base and interior organizer pockets — built for daily carry.",
    features: ["Heavy canvas construction", "Leather-trimmed base", "Interior zip pocket", "Fits a 14-inch laptop"],
    specs: { Material: "Canvas + PU leather trim", Capacity: "18L" },
    pros: ["Holds shape well", "Fits laptop + daily essentials"],
    cons: ["No shoulder strap included"],
    faqs: [{ question: "Does it fit a laptop?", answer: "Yes, up to 14 inches comfortably." }],
    rating: 4.5,
    reviewCount: 421,
    images: [img("tote-1"), img("tote-2")],
    pinterestImage: img("tote-pin"),
    pinterestTitle: "The Structured Tote That Fits Everything",
    pinterestDesc: "Work bag, everyday bag, and travel bag in one.",
    tags: ["bags", "tote", "work-bag"],
    affiliateNetwork: "MYNTRA",
    affiliateUrl: "https://www.myntra.com/example6",
    isBestSeller: true,
  },
];

export const blogPosts: BlogPost[] = [
  {
    id: "b1",
    title: "Best Shoes Under ₹2000 (Tested & Ranked)",
    slug: "best-shoes-under-2000",
    excerpt: "Nine pairs we actually wore for a month — here's what held up.",
    content: "Full article body goes here in MDX/markdown, with an auto-generated table of contents, internal links to /product/[slug] pages, and inline product cards.",
    featuredImage: img("blog-shoes"),
    author: "TrendNest Editorial",
    tags: ["shoes", "budget-picks"],
    relatedProductSlugs: ["cloudstep-running-sneakers"],
    publishedAt: "2026-06-01",
  },
  {
    id: "b2",
    title: "Top Fashion Trends This Season",
    slug: "top-fashion-trends",
    excerpt: "What's actually trending on Pinterest right now, not just Instagram.",
    content: "Full article body goes here.",
    featuredImage: img("blog-fashion"),
    author: "TrendNest Editorial",
    tags: ["fashion", "trends"],
    relatedProductSlugs: ["everyday-linen-wrap-dress", "classic-oxford-cotton-shirt"],
    publishedAt: "2026-06-08",
  },
  {
    id: "b3",
    title: "Best Amazon Finds This Month",
    slug: "best-amazon-finds",
    excerpt: "The under-the-radar picks worth the click.",
    content: "Full article body goes here.",
    featuredImage: img("blog-amazon"),
    author: "TrendNest Editorial",
    tags: ["amazon", "deals"],
    relatedProductSlugs: ["cloudstep-running-sneakers", "everyday-linen-wrap-dress"],
    publishedAt: "2026-06-15",
  },
  {
    id: "b4",
    title: "Home Decor Ideas That Don't Look Cheap",
    slug: "home-decor-ideas",
    excerpt: "Small pieces, big difference — a room-by-room guide.",
    content: "Full article body goes here.",
    featuredImage: img("blog-decor"),
    author: "TrendNest Editorial",
    tags: ["home-decor"],
    relatedProductSlugs: [],
    publishedAt: "2026-06-20",
  },
  {
    id: "b5",
    title: "Beauty Products Worth Buying (No Filler)",
    slug: "beauty-products-worth-buying",
    excerpt: "The routine upgrades that are actually worth your money.",
    content: "Full article body goes here.",
    featuredImage: img("blog-beauty"),
    author: "TrendNest Editorial",
    tags: ["beauty"],
    relatedProductSlugs: ["layered-gold-plated-necklace-set"],
    publishedAt: "2026-06-25",
  },
];

export const getProductBySlug = (slug: string) => products.find((p) => p.slug === slug);
export const getCategoryBySlug = (slug: string) => categories.find((c) => c.slug === slug);
export const getProductsByCategory = (slug: string) => products.filter((p) => p.categorySlug === slug);
export const getBlogPostBySlug = (slug: string) => blogPosts.find((b) => b.slug === slug);
export const getRelatedProducts = (product: Product, limit = 4) =>
  products.filter((p) => p.categorySlug === product.categorySlug && p.id !== product.id).slice(0, limit);
